# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.CharField(max_length=90)),
                ('node_sender', models.CharField(max_length=50)),
                ('node_receiver', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('transmission_power', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('Rss_mrc', models.CharField(max_length=20)),
                ('Rss_ant0', models.CharField(max_length=20)),
                ('Rss_ant1', models.CharField(max_length=20)),
                ('Rss_ant2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
            ],
        ),
    ]
