# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node_sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_sender_text', models.CharField(max_length=50)),
                ('node_receiver_text', models.CharField(max_length=50)),
                ('Time_text', models.CharField(max_length=200)),
                ('Rss_text', models.CharField(max_length=20)),
            ],
        ),
    ]
