# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Node_sender',
            new_name='Input',
        ),
    ]
