# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0003_uploadfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='Rss_text',
            new_name='Rss',
        ),
        migrations.RenameField(
            model_name='input',
            old_name='node_receiver_text',
            new_name='node_receiver',
        ),
        migrations.RenameField(
            model_name='input',
            old_name='node_sender_text',
            new_name='node_sender',
        ),
        migrations.RemoveField(
            model_name='input',
            name='Time_text',
        ),
        migrations.AddField(
            model_name='input',
            name='Timestamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='frequency',
            field=models.CharField(default=2412, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='rate',
            field=models.CharField(default=6, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='transmission_power',
            field=models.CharField(default=14, max_length=50),
            preserve_default=False,
        ),
    ]
