# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0004_auto_20170524_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='Timestamp',
            field=models.CharField(max_length=90),
        ),
    ]
